"""Add MatKhau fields

Revision ID: 3340d6e011ed
Revises: 
Create Date: 2025-12-12 00:03:36.297234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3340d6e011ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NhanVienKho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MatKhau', sa.String(length=255), nullable=True))

    with op.batch_alter_table('ThuNgan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MatKhau', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ThuNgan', schema=None) as batch_op:
        batch_op.drop_column('MatKhau')

    with op.batch_alter_table('NhanVienKho', schema=None) as batch_op:
        batch_op.drop_column('MatKhau')

    # ### end Alembic commands ###
